name: demo pipeline

on: 
    push: 
        branches:
            - main
            - dev
    pull_request:
        branches: [ main, dev ]
    # schedule:
    #     - cron: "*/1 * * * *"
jobs:
    setup_job:
        runs-on: ubuntu-latest      # macos-latest, windows-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: create file
              run: |
                touch github-action.txt
                echo "from first job" > github-action.txt
                ls -la
                echo "Hello World!"
                cat README.md
            - name: upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact-file
                path: github-action.txt
    build_job:
        needs: setup_job
        runs-on: ubuntu-latest
        steps:
            - name: display hello
              run: echo hello
            - name: download artifact
              uses: actions/upload-artifact@v4
              with:
                path: github-action.txt
            - name: display github-action.txt
              run: cat github-action.txt
    deploy_job:
        needs: build_job
        runs-on: macos-latest
        steps:
            - run: echo "Hello Mac"
           